### ISSUE TITLE
on plone6 branch, action "required" bool field cannot be set, thus no action is performed

### ISSUE THREAD

**Issue by yurj** [collective/collective.easyform#313] opened 2021-12-23 10:36 UTC
Hi!

 how to reproduce:

install easyform branch plone6
add a form
go in the action
try to enable the mailer action flagging it and saving
the action is not flagged, thus does not run when sending the email.

I don't know if it is related to some bool field changes but it worked a couple of weeks ago.

**Comment by yurj** [comment] 2021-12-23 10:41
I can fix it using @@actions/@@modeleditor and adding
`<required>True</required>`
If you save it again using the actions view, it will be lost and thus you're to set it again.

**Comment by yurj** [comment] 2021-12-23 10:58
I've found it is the same schema of the action itself, so also editing the action will erase it. It is like the `required` field it is not in the schema. I can see it just in the action init, where it is set to `False` but the field itself is not declared anywhere, at least with my limited knowledge in schema/forms/supermodel or whatever it is.

**Comment by frapell** [comment] 2022-01-11 18:37
Hitting the same issue on my side when trying this in Plone 6. Not sure what's the proper fix

**Comment by yurj** [comment] 2022-01-12 08:00
@jensens @mauritsvanrees maybe some changes on boolean/checkbox handling (z3c.form?)?

**Comment by mauritsvanrees** [comment] 2022-01-12 08:45
This looks like a bug that was fixed in latest zope.schema. Are you using that?

I expect this to work with Plone 6.0.0a2.

**Comment by frapell** [comment] 2022-01-12 11:58
@mauritsvanrees Yup, I can confirm https://github.com/zopefoundation/zope.schema/pull/107 does fix the issue with easyforms...

nice butterfly effect ;)

**Comment by yurj** [comment] 2022-01-12 13:22
> This looks like a bug that was fixed in latest zope.schema. Are you using that?
> 
> I expect this to work with Plone 6.0.0a2.

I'm using Plone 6.0.0a2 with `zope.schema 6.1.0` the fix is in `zope.schema 6.1.1`.

**Comment by petschki** [comment] 2022-01-21 10:01
This can be closed as solved with updated `zope.schema`

**Closed by petschki** 2022-01-21 10:01 UTC
Labels: bug, critical

**Comment by frapell** [comment] 2022-01-21 12:06
@petschki I was thinking maybe we want to pin zope.schema >= 6.1.1 in setup.py ?
