### ISSUE TITLE
New fields are always added to the "default" fieldset instead to the current fieldset

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#73] opened 2017-06-12 16:26 UTC
Plone 5.1, collective.easyform2.0.0a..

Creating a new field within the context of a fieldset has the effect that the field is alway added to the default fieldset instead of to the current fieldset.

**Comment by thet** [comment] 2017-06-12 16:58
Duplicate of https://github.com/collective/collective.easyform/issues/50 and fixed here: https://github.com/plone/plone.schemaeditor/pull/54

This was actually a problem with plone.schemaeditor and also broken for the Dexterity schema editing form.

**Closed by thet** 2017-06-12 16:58 UTC

**Comment by zopyx** [comment] 2017-06-12 17:13
The error is persistent in at least the latested plone.schemaeditor 2.0.17 release

**Comment by tomgross** [comment] 2017-06-13 18:57
A recent mockup is needed too. AFAIK there is no release yet.
